ingredients = [
        {"name" : "Beef", "ingredient_type" : "meats"},
        {"name" : "Bacon", "ingredient_type" : "meats"},
        {"name" : "Fish", "ingredient_type" : "meats"},
        {"name" : "Lamb", "ingredient_type" : "meats"},
        {"name" : "Beef mince", "ingredient_type" : "meats"},
        {"name" : "Cod", "ingredient_type" : "meats"},
        {"name" : "Chicken", "ingredient_type" : "meats"},
        {"name" : "Pork mince", "ingredient_type" : "meats"},
        {"name" : "Salmon", "ingredient_type" : "meats"},
        {"name" : "Pork", "ingredient_type" : "meats"},
        {"name" : "Soy mince", "ingredient_type" : "meats"},
        {"name" : "Lobster", "ingredient_type" : "meats"},
        {"name" : "Lamb chop", "ingredient_type" : "meats"},
        {"name" : "Seitan", "ingredient_type" : "meats"},
        {"name" : "Shrimp", "ingredient_type" : "meats"},
        {"name" : "Pork chop", "ingredient_type" : "meats"},
        {"name" : "Tempeh", "ingredient_type" : "meats"},
        {"name" : "Muscle", "ingredient_type" : "meats"},
        {"name" : "Pork sausage", "ingredient_type" : "meats"},
        {"name" : "Vegan sausage", "ingredient_type" : "meats"},
        {"name" : "Caviar", "ingredient_type" : "meats"},
        {"name" : "Chicken breast", "ingredient_type" : "meats"},
        
        
        
        {"name" : "Milk", "ingredient_type" : "dairy"},
        {"name" : "Cheese", "ingredient_type" : "dairy"},
        {"name" : "Cream", "ingredient_type" : "dairy"},
        {"name" : "Skim milk", "ingredient_type" : "dairy"},
        {"name" : "Cheddar", "ingredient_type" : "dairy"},
        {"name" : "Double cream", "ingredient_type" : "dairy"},
        {"name" : "Oat milk", "ingredient_type" : "dairy"},
        {"name" : "Parmesan", "ingredient_type" : "dairy"},
        {"name" : "Plain yoghurt", "ingredient_type" : "dairy"},
        {"name" : "Almond milk", "ingredient_type" : "dairy"},
        {"name" : "Red Leicester", "ingredient_type" : "dairy"},
        {"name" : "Greek yoghurt", "ingredient_type" : "dairy"},
        {"name" : "Soy milk", "ingredient_type" : "dairy"},
        {"name" : "Goat cheese", "ingredient_type" : "dairy"},
        {"name" : "Egg", "ingredient_type" : "dairy"},
        {"name" : "Cashew milk", "ingredient_type" : "dairy"},
        {"name" : "Blue cheese", "ingredient_type" : "dairy"},
        {"name" : "Quail egg", "ingredient_type" : "dairy"},
        {"name" : "Vegan cheese", "ingredient_type" : "dairy"},
        {"name" : "Quark", "ingredient_type" : "dairy"},
        {"name" : "Pickled egg", "ingredient_type" : "dairy"},
        {"name" : "Vegan parmesan", "ingredient_type" : "dairy"},
        
        
        {"name" : "Tomato", "ingredient_type" : "veg"},
        {"name" : "Potato", "ingredient_type" : "veg"},
        {"name" : "Broccoli", "ingredient_type" : "veg"},
        {"name" : "Cherry tomato", "ingredient_type" : "veg"},
        {"name" : "Baby potato", "ingredient_type" : "veg"},
        {"name" : "Asparaggus", "ingredient_type" : "veg"},
        {"name" : "Cucumber", "ingredient_type" : "veg"},
        {"name" : "Sweet potato", "ingredient_type" : "veg"},
        {"name" : "Red pepper", "ingredient_type" : "veg"},
        {"name" : "Lettuce", "ingredient_type" : "veg"},
        {"name" : "Carrot", "ingredient_type" : "veg"},
        {"name" : "Green pepper", "ingredient_type" : "veg"},
        {"name" : "Arugula", "ingredient_type" : "veg"},
        {"name" : "Sweetcorn", "ingredient_type" : "veg"},
        {"name" : "Yellow pepper", "ingredient_type" : "veg"},
        {"name" : "Radicchio", "ingredient_type" : "veg"},
        {"name" : "Baby corn", "ingredient_type" : "veg"}, 
        {"name" : "Sweet pepper", "ingredient_type" : "veg"},
        {"name" : "Salad leaves", "ingredient_type" : "veg"},
        {"name" : "Green bean", "ingredient_type" : "veg"},
        {"name" : "Button mushroom", "ingredient_type" : "veg"},
        {"name" : "Onion", "ingredient_type" : "veg"},
        {"name" : "Zucchini", "ingredient_type" : "veg"},
        {"name" : "Chestnut mushroom", "ingredient_type" : "veg"},
        {"name" : "Red onion", "ingredient_type" : "veg"},
        {"name" : "Aubergine", "ingredient_type" : "veg"},
        {"name" : "Portobello", "ingredient_type" : "veg"},
        {"name" : "Fresh onion", "ingredient_type" : "veg"},
        {"name" : "Avocado", "ingredient_type" : "veg"},
        {"name" : "Shiitake", "ingredient_type" : "veg"},
        {"name" : "Leek", "ingredient_type" : "veg"},
        {"name" : "Nutritional yeast", "ingredient_type" : "veg"},
        {"name" : "Wild mushroom", "ingredient_type" : "veg"},
        {"name" : "Garlic", "ingredient_type" : "veg"},
        
        {"name" : "Brown lentil", "ingredient_type" : "pulses"},
        {"name" : "Kidney bean", "ingredient_type" : "pulses"},
        {"name" : "Chickpea", "ingredient_type" : "pulses"},
        {"name" : "Red lentil", "ingredient_type" : "pulses"},
        {"name" : "Black bean", "ingredient_type" : "pulses"},
        {"name" : "Garden pea", "ingredient_type" : "pulses"},
        {"name" : "Yellow lentil", "ingredient_type" : "pulses"},
        {"name" : "Pinto bean", "ingredient_type" : "pulses"},
        {"name" : "Cannellini bean", "ingredient_type" : "pulses"},
        {"name" : "Green lentil", "ingredient_type" : "pulses"},
        {"name" : "Haricot", "ingredient_type" : "pulses"},
        {"name" : "Broad bean", "ingredient_type" : "pulses"},
        {"name" : "Puy lentil", "ingredient_type" : "pulses"},
        {"name" : "Black-eyed bean", "ingredient_type" : "pulses"},
        {"name" : "Baked bean", "ingredient_type" : "pulses"},
        {"name" : "Belunga lentil", "ingredient_type" : "pulses"},

        {"name" : "Quinoa", "ingredient_type" : "grains"},
        {"name" : "Chia seed", "ingredient_type" : "grains"},
        {"name" : "Almond", "ingredient_type" : "grains"},
        {"name" : "Barley", "ingredient_type" : "grains"},
        {"name" : "Poppy seed", "ingredient_type" : "grains"},
        {"name" : "Peanut", "ingredient_type" : "grains"},
        {"name" : "Bulgur wheat", "ingredient_type" : "grains"},
        {"name" : "Flax seed", "ingredient_type" : "grains"},
        {"name" : "Hazelnut", "ingredient_type" : "grains"},
        {"name" : "Rye", "ingredient_type" : "grains"},
        {"name" : "Sesame seed", "ingredient_type" : "grains"},
        {"name" : "Cashew", "ingredient_type" : "grains"},
        {"name" : "Grits", "ingredient_type" : "grains"},
        {"name" : "Pine nut", "ingredient_type" : "grains"},
        {"name" : "Walnut", "ingredient_type" : "grains"},
        {"name" : "Cereal", "ingredient_type" : "grains"},
        {"name" : "Pistachio", "ingredient_type" : "grains"},
        {"name" : "Pecan", "ingredient_type" : "grains"},
        {"name" : "Pumpkin seed", "ingredient_type" : "grains"},
        {"name" : "Brazil nut", "ingredient_type" : "grains"},
        {"name" : "Macademia nut", "ingredient_type" : "grains"},
        {"name" : "Sunflower seed", "ingredient_type" : "grains"},
        {"name" : "Mixed nut", "ingredient_type" : "grains"},
        
        {"name" : "Bread", "ingredient_type" : "carbs"},
        {"name" : "Tortilla", "ingredient_type" : "carbs"},
        {"name" : "Rice", "ingredient_type" : "carbs"},
        {"name" : "Sliced bread", "ingredient_type" : "carbs"},
        {"name" : "Pasta", "ingredient_type" : "carbs"},
        {"name" : "Basmati rice", "ingredient_type" : "carbs"},
        {"name" : "Ciabatta loaf", "ingredient_type" : "carbs"},
        {"name" : "Spaghetti", "ingredient_type" : "carbs"},
        {"name" : "Sticky rice", "ingredient_type" : "carbs"},
        {"name" : "Naan bread", "ingredient_type" : "carbs"},
        {"name" : "Tagliatelle", "ingredient_type" : "carbs"},
        {"name" : "Wild rice", "ingredient_type" : "carbs"},
        {"name" : "Pitta", "ingredient_type" : "carbs"},
        {"name" : "Fusilli", "ingredient_type" : "carbs"},
        {"name" : "Brown rice", "ingredient_type" : "carbs"},
        {"name" : "Burger bun", "ingredient_type" : "carbs"},
        {"name" : "Penne", "ingredient_type" : "carbs"},
        {"name" : "Noodle", "ingredient_type" : "carbs"},

        {"name" : "Olive oil", "ingredient_type" : "fats"},
        {"name" : "Avocado oil", "ingredient_type" : "fats"},
        {"name" : "Butter", "ingredient_type" : "fats"},
        {"name" : "EEVO", "ingredient_type" : "fats"},
        {"name" : "Coconut oil", "ingredient_type" : "fats"},
        {"name" : "Clarified butter", "ingredient_type" : "fats"},
        {"name" : "Sunflower oil", "ingredient_type" : "fats"},
        {"name" : "Sesame oil", "ingredient_type" : "fats"},
        {"name" : "Margarine", "ingredient_type" : "fats"},
        {"name" : "Rapeseed oil", "ingredient_type" : "fats"},
        {"name" : "Hemp seed oil", "ingredient_type" : "fats"},
        {"name" : "Duck fat", "ingredient_type" : "fats"},
        {"name" : "Canola oil", "ingredient_type" : "fats"},
        {"name" : "Chilli oil", "ingredient_type" : "fats"},
        {"name" : "Suet", "ingredient_type" : "fats"},
        {"name" : "Grapeseed oil", "ingredient_type" : "fats"},
        {"name" : "Vegetable oil", "ingredient_type" : "fats"},
        {"name" : "Lard", "ingredient_type" : "fats"},
        {"name" : "Shortening", "ingredient_type" : "fats"},
        
        
        
        {"name" : "Salt", "ingredient_type" : "herbs"},
        {"name" : "Cumin", "ingredient_type" : "herbs"},
        {"name" : "Thyme", "ingredient_type" : "herbs"},
        {"name" : "Kosher salt", "ingredient_type" : "herbs"},
        {"name" : "Coriander", "ingredient_type" : "herbs"},
        {"name" : "Bay leaf", "ingredient_type" : "herbs"},
        {"name" : "Sea salt", "ingredient_type" : "herbs"},
        {"name" : "Cinnamon", "ingredient_type" : "herbs"},
        {"name" : "Parsley", "ingredient_type" : "herbs"},
        {"name" : "Pink salt", "ingredient_type" : "herbs"},
        {"name" : "Nutmeg", "ingredient_type" : "herbs"},
        {"name" : "Sage", "ingredient_type" : "herbs"},
        {"name" : "Himalayan salt", "ingredient_type" : "herbs"},
        {"name" : "Clove", "ingredient_type" : "herbs"},
        {"name" : "Rosemary", "ingredient_type" : "herbs"},
        {"name" : "Black pepper", "ingredient_type" : "herbs"},
        {"name" : "Cardamom", "ingredient_type" : "herbs"},
        {"name" : "Oregano", "ingredient_type" : "herbs"},
        {"name" : "White pepper", "ingredient_type" : "herbs"},
        {"name" : "Allspice", "ingredient_type" : "herbs"},
        {"name" : "Basil", "ingredient_type" : "herbs"},
        {"name" : "Cayenne pepper", "ingredient_type" : "herbs"},
        {"name" : "Ground ginger", "ingredient_type" : "herbs"},
        {"name" : "Italian seasoning", "ingredient_type" : "herbs"},
        {"name" : "Paprika", "ingredient_type" : "herbs"},
        {"name" : "Marjoram", "ingredient_type" : "herbs"},
        {"name" : "Fennel", "ingredient_type" : "herbs"},
        {"name" : "Turmeric", "ingredient_type" : "herbs"},
        {"name" : "Saffron", "ingredient_type" : "herbs"},
        {"name" : "Fenugreek", "ingredient_type" : "herbs"},
        {"name" : "Cajun seasoning", "ingredient_type" : "herbs"},
        {"name" : "Star anise", "ingredient_type" : "herbs"},
        {"name" : "Peppermint", "ingredient_type" : "herbs"},
        {"name" : "Curry", "ingredient_type" : "herbs"},
        {"name" : "Celery seed", "ingredient_type" : "herbs"},
        {"name" : "Spearmint", "ingredient_type" : "herbs"},
        {"name" : "Garam masala", "ingredient_type" : "herbs"},
        {"name" : "Wasabi", "ingredient_type" : "herbs"},
        {"name" : "Cilantro", "ingredient_type" : "herbs"},
        {"name" : "Garlic powder", "ingredient_type" : "herbs"},
        {"name" : "Dill", "ingredient_type" : "herbs"},


        {"name" : "Ketchup", "ingredient_type" : "condiments"},
        {"name" : "Soy sauce", "ingredient_type" : "condiments"},
        {"name" : "Brown sauce", "ingredient_type" : "condiments"},
        {"name" : "BBQ sauce", "ingredient_type" : "condiments"},
        {"name" : "Liquid smoke", "ingredient_type" : "condiments"},
        {"name" : "Worcestershire", "ingredient_type" : "condiments"},
        {"name" : "Mayonnaise", "ingredient_type" : "condiments"},
        {"name" : "Tomato passata", "ingredient_type" : "condiments"},
        {"name" : "Fish sauce", "ingredient_type" : "condiments"},
        {"name" : "Mustard", "ingredient_type" : "condiments"},
        {"name" : "Sauerkraut", "ingredient_type" : "condiments"},
        {"name" : "Oyster sauce", "ingredient_type" : "condiments"},
        {"name" : "Honey mustard", "ingredient_type" : "condiments"},
        {"name" : "Lamb stock", "ingredient_type" : "condiments"},
        
        {"name" : "Red apple", "ingredient_type" : "fruit"},
        {"name" : "Orange", "ingredient_type" : "fruit"},
        {"name" : "Strawberry", "ingredient_type" : "fruit"},
        {"name" : "Granny smith", "ingredient_type" : "fruit"},
        {"name" : "Mandarin", "ingredient_type" : "fruit"},
        {"name" : "Blueberry", "ingredient_type" : "fruit"},
        {"name" : "Pear", "ingredient_type" : "fruit"},
        {"name" : "Grapefruit", "ingredient_type" : "fruit"},
        {"name" : "Raspberry", "ingredient_type" : "fruit"},
        {"name" : "Banana", "ingredient_type" : "fruit"},
        {"name" : "Pomelo", "ingredient_type" : "fruit"},
        {"name" : "Blackberry", "ingredient_type" : "fruit"},
        {"name" : "Peach", "ingredient_type" : "fruit"},
        {"name" : "Lemon", "ingredient_type" : "fruit"},
        {"name" : "Cranberry", "ingredient_type" : "fruit"},
        {"name" : "Apricot", "ingredient_type" : "fruit"},
        {"name" : "Lime", "ingredient_type" : "fruit"},
        {"name" : "Pomegranate", "ingredient_type" : "fruit"},


        {"name" : "Sugar", "ingredient_type" : "baking"},
        {"name" : "Dark chocolate", "ingredient_type" : "baking"},
        {"name" : "Flour", "ingredient_type" : "baking"},
        {"name" : "Brown sugar", "ingredient_type" : "baking"},
        {"name" : "Milk chocolate", "ingredient_type" : "baking"},
        {"name" : "Self-rising flour", "ingredient_type" : "baking"},
        {"name" : "Honey", "ingredient_type" : "baking"},
        {"name" : "White chocolate", "ingredient_type" : "baking"},
        {"name" : "Wholewheat flour", "ingredient_type" : "baking"},
        {"name" : "Maple syrup", "ingredient_type" : "baking"},
        {"name" : "Chocolate chip", "ingredient_type" : "baking"},
        {"name" : "Corn flour", "ingredient_type" : "baking"},
        {"name" : "Agave", "ingredient_type" : "baking"},
        {"name" : "Biscuit", "ingredient_type" : "baking"},
        {"name" : "Oatmeal", "ingredient_type" : "baking"},
        {"name" : "Vanilla extract", "ingredient_type" : "baking"},
        {"name" : "Ice cream", "ingredient_type" : "baking"},
        {"name" : "Baking powder", "ingredient_type" : "baking"},
        {"name" : "Caramel", "ingredient_type" : "baking"},
        {"name" : "Puff pastry", "ingredient_type" : "baking"},
        {"name" : "Yeast", "ingredient_type" : "baking"},
        {"name" : "Dulce de leche", "ingredient_type" : "baking"},
        
        {"name" : "Water", "ingredient_type" : "drinks"},
        {"name" : "Coffee", "ingredient_type" : "drinks"},
        {"name" : "Red wine", "ingredient_type" : "drinks"},
        {"name" : "Orange juice", "ingredient_type" : "drinks"},  
        {"name" : "Espresso", "ingredient_type" : "drinks"}, 
        {"name" : "White wine", "ingredient_type" : "drinks"}, 
        {"name" : "Apple juice", "ingredient_type" : "drinks"},
        {"name" : "Black tea", "ingredient_type" : "drinks"},
        {"name" : "Beer", "ingredient_type" : "drinks"}, 
        {"name" : "Green tea", "ingredient_type" : "drinks"},
        {"name" : "Brandy", "ingredient_type" : "drinks"},
        {"name" : "Whiskey", "ingredient_type" : "drinks"},
        {"name" : "Matcha tea", "ingredient_type" : "drinks"},
        {"name" : "Ice tea", "ingredient_type" : "drinks"},  
        {"name" : "Gin", "ingredient_type" : "drinks"},
        {"name" : "Chamomile tea", "ingredient_type" : "drinks"},
        
    ]
    
    
def get_all_ingredients():
    return ingredients