# Generated by Django 2.2.26 on 2022-02-28 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('ingredient_type', models.CharField(choices=[('meats', 'Meat, Seafood & Substitutes'), ('dairy', 'Eggs, Dairy & Substitutes'), ('veg', 'Vegetables & Funghi'), ('pulses', 'Pulses'), ('grains', 'Grains, Seeds & Nuts'), ('carbs', 'Bread, Pasta & Rice'), ('fats', 'Fats & Oils'), ('herbs', 'Herbs & Spices'), ('condiments', 'Condiments & Sauces'), ('fruit', 'Fruit'), ('sweets', 'Sweet & Baking'), ('drinks', 'Beverages')], max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_pictures')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_pictures')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('steps', models.CharField(max_length=2048)),
                ('prep_time', models.IntegerField()),
                ('cook_time', models.IntegerField()),
                ('servings', models.IntegerField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('advanced', 'Advanced')], max_length=16)),
                ('picture', models.ImageField(blank=True, upload_to='recipe_pictures')),
                ('pub_date', models.DateField()),
                ('stars', models.IntegerField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pantry.SiteUser')),
                ('category', models.ManyToManyField(to='pantry.Category')),
                ('ingredients', models.ManyToManyField(to='pantry.Ingredient')),
            ],
        ),
    ]
