# Generated by Django 2.2.26 on 2022-03-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='starred',
            field=models.ManyToManyField(related_name='users', to='pantry.Recipe'),
        ),
    ]
