# Generated by Django 2.2.26 on 2022-02-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=128)),
                ('Type', models.CharField(choices=[('meat', 'Meat, seafood & substitutes'), ('eggs', 'Eggs, dairy & substitutes'), ('veg', 'Vegetables & Funghi'), ('pulses', 'Pulses'), ('grains', 'Grains, seeds & nuts'), ('bread', 'Bread, pasta & rice'), ('fats', 'Fats & Oils'), ('herbs', 'Herbs & Spices'), ('condiments', 'Condiments & Sauces'), ('fruit', 'Fruit'), ('sweets', 'Sweet & Baking'), ('beverages', 'Beverages')], max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=128)),
                ('Steps', models.CharField(max_length=2048)),
                ('PrepTime', models.IntegerField()),
                ('CookTime', models.IntegerField()),
                ('Servings', models.IntegerField()),
                ('Difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=16)),
                ('Picture', models.ImageField(blank=True, upload_to='recipe_pictures')),
                ('PubDate', models.DateField()),
                ('Start', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=254)),
                ('Username', models.CharField(max_length=128)),
                ('Password', models.CharField(max_length=128)),
                ('ProfilePicture', models.ImageField(blank=True, upload_to='profile_pictures')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pictures'),
        ),
    ]
