# Generated by Django 2.2.26 on 2022-03-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientlist',
            name='plural',
            field=models.BooleanField(default=False),
        ),
    ]
