# Generated by Django 2.2.26 on 2022-02-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0002_auto_20220228_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='Ingredients',
            field=models.ManyToManyField(to='pantry.Ingredient'),
        ),
    ]
