# Generated by Django 2.2.26 on 2022-02-28 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0003_recipe_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Start',
            new_name='Stars',
        ),
    ]
