# Generated by Django 2.2.26 on 2022-02-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0004_auto_20220228_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='Category',
            field=models.ManyToManyField(to='pantry.Category'),
        ),
    ]
