# Generated by Django 2.2.26 on 2022-02-28 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0005_recipe_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
