# Generated by Django 2.2.26 on 2022-02-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0006_auto_20220228_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='Author',
            field=models.ManyToManyField(to='pantry.UserProfile'),
        ),
    ]
