# Generated by Django 2.2.26 on 2022-02-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0007_recipe_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Author',
            field=models.ManyToManyField(to='pantry.User'),
        ),
    ]
