# Generated by Django 2.2.26 on 2022-02-28 19:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0008_auto_20220228_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Recipes',
            field=models.ManyToManyField(to='pantry.Recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Author',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
