# Generated by Django 2.2.26 on 2022-02-28 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0009_auto_20220228_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=254)),
                ('Username', models.CharField(max_length=128)),
                ('Password', models.CharField(max_length=128)),
                ('ProfilePicture', models.ImageField(blank=True, upload_to='profile_pictures')),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='Author',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='recipe',
            name='Author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pantry.SiteUser'),
        ),
    ]
