# Generated by Django 2.2.26 on 2022-02-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0010_auto_20220228_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='Name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Title',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='Email',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='Username',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
