# Generated by Django 2.2.26 on 2022-02-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0011_auto_20220228_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='Type',
            field=models.CharField(choices=[('meats', 'Meat, seafood & substitutes'), ('dairy', 'Eggs, dairy & substitutes'), ('veg', 'Vegetables & Funghi'), ('pulses', 'Pulses'), ('grains', 'Grains, seeds & nuts'), ('carbs', 'Bread, pasta & rice'), ('fats', 'Fats & Oils'), ('herbs', 'Herbs & Spices'), ('condiments', 'Condiments & Sauces'), ('fruit', 'Fruit'), ('sweets', 'Sweet & Baking'), ('drinks', 'Beverages')], max_length=128),
        ),
    ]
